version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=developmen
    depends_on:
      - redis
      - mongo

  frontend:
    build:
      context: ./frontend/chatapp
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
